project:
  type: website
website:
  title: "Tracking Error Notes"
  navbar:
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Intuitive Math"
        href: intuitive_math.qmd
      - text: "Technical Math"
        href: technical_math.qmd
    right:
      - text: "Interactive App"
        href: https://tracking-error-lab-kgkju98o4pqxdjoevqtsay.streamlit.app/
      - text: "GitHub Repo"
        href: https://github.com/TejasViswa/tracking-error-lab
format:
  html:
    theme: cosmo
    toc: true
    math: mathjax
    page-layout: full
    css: styles.css
