project:
  type: website
website:
  title: "Tracking Error Notes"
  navbar:
    right:
      - text: "Interactive App"
        href: https://tracking-error-lab-kgkju98o4pqxdjoevqtsay.streamlit.app/
format:
  html:
    theme: flatly
    toc: true
    math: mathjax
    mainfont: "Roboto"
    css: styles.css
