project:
  type: website
website:
  title: "Tracking Error Lab"
  navbar:
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Intuitive Math"
        href: intuitive_math.qmd
      - text: "Technical Math"
        href: technical_math.qmd
    right:
      - icon: box-arrow-up-right
        text: "Interactive App"
        href: https://tracking-error-lab-kgkju98o4pqxdjoevqtsay.streamlit.app/
      - icon: github
        text: "GitHub"
        href: https://github.com/TejasViswa/tracking-error-lab
  page-footer:
    left: |
      **Tejas Viswanath** | 
      [<i class="bi bi-linkedin"></i> LinkedIn](https://www.linkedin.com/in/tejasviswa/) | 
      [<i class="bi bi-github"></i> GitHub](https://github.com/TejasViswa/) | 
      [<i class="bi bi-envelope"></i> Email](mailto:tejasviswa@gmail.com)
    center: "Â© 2025 Tracking Error Lab"
    right: |
      Built with [Quarto](https://quarto.org)
format:
  html:
    theme: cosmo
    toc: true
    math: mathjax
    page-layout: full
    css: styles.css
